#!/bin/sh


app="webbooks_test"
venv="../venv"

pidfile="/tmp/gunicorn_${app}.pid"
socket="/tmp/${app}_server.socket"

[ -e "$pidfile" ] && xargs -a "$pidfile" kill

"$venv/bin/python" manage.py collectstatic --noinput

urxvt -e "$venv/bin/gunicorn" --pid "$pidfile" \
--bind unix:"$socket" project.wsgi:application &
